import type { Metadata } from "next";
import { Inter, Chakra_Petch } from "next/font/google";
import "./styles/globals.css";
import "./styles/styles.css";
import "./styles/customWalletStyles.css";

import { Providers } from "./providers";

// const inter = Inter({ subsets: ["latin"] });
const chakra = Chakra_Petch({ weight: "600", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={chakra.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
